/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.39
 * Generated at: 2025-04-02 07:02:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Ex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>Navi Menu JSP Example</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"navi.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-family: \"Lato\", sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @media screen and (max-width: 700px) {\r\n");
      out.write("            body {\r\n");
      out.write("                padding: 170px 0 0 0;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        a {\r\n");
      out.write("            color: inherit;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-item,\r\n");
      out.write("        .menu-open-button {\r\n");
      out.write("            background: #EEEEEE;\r\n");
      out.write("            border-radius: 100%;\r\n");
      out.write("            width: 50px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            margin-left: -25px; \r\n");
      out.write("            line-height: 50px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            color: #FFFFFF;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            transform: translate3d(0, 0, 0);\r\n");
      out.write("            transition: transform ease-out 200ms;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-open {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .lines {\r\n");
      out.write("            width: 25px;\r\n");
      out.write("            height: 3px;\r\n");
      out.write("            background: #596778;\r\n");
      out.write("            display: block;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            margin-left: -12.5px;\r\n");
      out.write("            margin-top: -1.5px;\r\n");
      out.write("            transition: transform 200ms;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .line-1 {\r\n");
      out.write("            transform: translate3d(0, -8px, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .line-2 {\r\n");
      out.write("            transform: translate3d(0, 0, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .line-3 {\r\n");
      out.write("            transform: translate3d(0, 8px, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-open:checked + .menu-open-button .line-1 {\r\n");
      out.write("            transform: translate3d(0, 0, 0) rotate(45deg);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-open:checked + .menu-open-button .line-2 {\r\n");
      out.write("            transform: translate3d(0, 0, 0) scale(0.1, 1);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-open:checked + .menu-open-button .line-3 {\r\n");
      out.write("            transform: translate3d(0, 0, 0) rotate(-45deg);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu {\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 10%; /* 상단 여백 */\r\n");
      out.write("            left: 8%; /* 좌측 여백 */\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-size: 26px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-item:hover {\r\n");
      out.write("            background: #EEEEEE;\r\n");
      out.write("            color: #3290B1;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-item:nth-child(3) {\r\n");
      out.write("            transition-duration: 180ms;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-item:nth-child(4) {\r\n");
      out.write("            transition-duration: 180ms;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-item:nth-child(5) {\r\n");
      out.write("            transition-duration: 180ms;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-item:nth-child(6) {\r\n");
      out.write("            transition-duration: 180ms;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-item:nth-child(7) {\r\n");
      out.write("            transition-duration: 180ms;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-item:nth-child(8) {\r\n");
      out.write("            transition-duration: 180ms;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-item:nth-child(9) {\r\n");
      out.write("            transition-duration: 180ms;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-open-button {\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("            transition-timing-function: cubic-bezier(0.175, 0.885, 0.32, 1.275);\r\n");
      out.write("            transition-duration: 400ms;\r\n");
      out.write("            transform: scale(1.1, 1.1);\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            box-shadow: 3px 3px 0 0 rgba(0, 0, 0, 0.14);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-open-button:hover {\r\n");
      out.write("            transform: scale(1.2, 1.2);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-open:checked + .menu-open-button {\r\n");
      out.write("            transition-timing-function: linear;\r\n");
      out.write("            transition-duration: 200ms;\r\n");
      out.write("            transform: scale(0.8, 0.8);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-open:checked ~ .menu-item {\r\n");
      out.write("            transition-timing-function: cubic-bezier(0.935, 0, 0.34, 1.33);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-open:checked ~ .menu-item:nth-child(3) {\r\n");
      out.write("            transition-duration: 180ms;\r\n");
      out.write("            transform: translate3d(0.06271px, -78.74998px, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-open:checked ~ .menu-item:nth-child(4) {\r\n");
      out.write("            transition-duration: 280ms;\r\n");
      out.write("            transform: translate3d(68.20995px, -39.35690px, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-open:checked ~ .menu-item:nth-child(5) {\r\n");
      out.write("            transition-duration: 380ms;\r\n");
      out.write("            transform: translate3d(68.20995px, 39.35690px, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-open:checked ~ .menu-item:nth-child(6) {\r\n");
      out.write("            transition-duration: 480ms;\r\n");
      out.write("            transform: translate3d(0.06271px, 78.74998px, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-open:checked ~ .menu-item:nth-child(7) {\r\n");
      out.write("            transition-duration: 580ms;\r\n");
      out.write("            transform: translate3d(-68.14718px, 39.46548px, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-open:checked ~ .menu-item:nth-child(8) {\r\n");
      out.write("            transition-duration: 680ms;\r\n");
      out.write("            transform: translate3d(-68.27255px, -39.24821px, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-open:checked ~ .menu-item:nth-child(9) {\r\n");
      out.write("            transition-duration: 780ms;\r\n");
      out.write("            transform: translate3d(-0.18813px, -78.74977px, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-item.blue {\r\n");
      out.write("            background: url('https://cdn-icons-png.flaticon.com/128/2948/2948025.png') no-repeat center center;\r\n");
      out.write("            background-size: 60%;\r\n");
      out.write("            background-color: #669AE1;\r\n");
      out.write("            box-shadow: 3px 3px 0 0 rgba(0, 0, 0, 0.14);\r\n");
      out.write("            text-shadow: 1px 1px 0 rgba(0, 0, 0, 0.12);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-item.blue:hover {\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            text-shadow: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-item.green {\r\n");
      out.write("            background: url('https://cdn-icons-png.flaticon.com/128/5264/5264565.png') no-repeat center center;\r\n");
      out.write("            background-color: #70CC72;\r\n");
      out.write("            background-size: 60%;\r\n");
      out.write("            box-shadow: 3px 3px 0 0 rgba(0, 0, 0, 0.14);\r\n");
      out.write("            text-shadow: 1px 1px 0 rgba(0, 0, 0, 0.12);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .menu-item.green:hover {\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            text-shadow: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .red {\r\n");
      out.write("            background-color: #FE4365;\r\n");
      out.write("            box-shadow: 3px 3px 0 0 rgba(0, 0, 0, 0.14);\r\n");
      out.write("            text-shadow: 1px 1px 0 rgba(0, 0, 0, 0.12);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .red:hover {\r\n");
      out.write("            color: #FE4365;\r\n");
      out.write("            text-shadow: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .purple {\r\n");
      out.write("            background-color: #C49CDE;\r\n");
      out.write("            box-shadow: 3px 3px 0 0 rgba(0, 0, 0, 0.14);\r\n");
      out.write("            text-shadow: 1px 1px 0 rgba(0, 0, 0, 0.12);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .purple:hover {\r\n");
      out.write("            color: #C49CDE;\r\n");
      out.write("            text-shadow: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .orange {\r\n");
      out.write("            background-color: #FC913A;\r\n");
      out.write("            box-shadow: 3px 3px 0 0 rgba(0, 0, 0, 0.14);\r\n");
      out.write("            text-shadow: 1px 1px 0 rgba(0, 0, 0, 0.12);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .orange:hover {\r\n");
      out.write("            color: #FC913A;\r\n");
      out.write("            text-shadow: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .lightblue {\r\n");
      out.write("            background-color: #62C2E4;\r\n");
      out.write("            box-shadow: 3px 3px 0 0 rgba(0, 0, 0, 0.14);\r\n");
      out.write("            text-shadow: 1px 1px 0 rgba(0, 0, 0, 0.12);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .lightblue:hover {\r\n");
      out.write("            color: #62C2E4;\r\n");
      out.write("            text-shadow: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .credit {\r\n");
      out.write("            margin: 24px 20px 120px 0;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            color: #EEEEEE;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .credit a {\r\n");
      out.write("            padding: 8px 0;\r\n");
      out.write("            color: #C49CDE;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            transition: all 0.3s ease 0s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .credit a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"menu\">\r\n");
      out.write("        <input type=\"checkbox\" class=\"menu-open\" name=\"menu-open\" id=\"menu-open\" />\r\n");
      out.write("        <label class=\"menu-open-button\" for=\"menu-open\">\r\n");
      out.write("            <span class=\"lines line-1\"></span>\r\n");
      out.write("            <span class=\"lines line-2\"></span>\r\n");
      out.write("            <span class=\"lines line-3\"></span>\r\n");
      out.write("        </label>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"../main/Main_Page.html\" class=\"menu-item blue\"></a>\r\n");
      out.write("        <a href=\"../login/login.html\" class=\"menu-item green\"></a>\r\n");
      out.write("        <a href=\"../BSH1/index.html\" class=\"menu-item red\">배</a>\r\n");
      out.write("        <a href=\"../profile_01/profile_jihun.html\" class=\"menu-item purple\">김</a>\r\n");
      out.write("        <a href=\"#\" class=\"menu-item orange\">여</a>\r\n");
      out.write("        <a href=\"#\" class=\"menu-item lightblue\">이</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
